version: "3.1"
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  # MySQL Data
  sparta_mysql_data:
    driver: local

services:

    mysql:
      image: mysql:5.7
      container_name: mysql
      working_dir: /var/lib/mysql
      networks:
        static-network:
          ipv4_address: 172.20.130.10
      volumes:
        - sparta_mysql_data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=ZsQ2vU6tm0
        - MYSQL_DATABASE=sparta
        - MYSQL_USER=system
        - MYSQL_PASSWORD=3dA5TF9I
      ports:
        - "3306:3306"

    app:
      image: ambientum/php:7.2-nginx
      container_name: web
      working_dir: /var/www/app
      networks:
        static-network:
          ipv4_address: 172.20.130.4
      volumes:
          - .:/var/www/app
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
          - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php7/php.ini
      ports:
        - "800:8080"
      links:
        - mysql

    nodejs:
      build: phpdocker/nodejs
      container_name: nodejs
      working_dir: /code
      volumes:
        - /srv/code:/code
      networks:
        static-network:
          ipv4_address: 172.20.130.9
      tty: true